#!/usr/bin/env python3
"""机构认证登录向导：用 CloakBrowser 打开机构登录页，用户手动完成登录，
脚本把会话 cookie 导出为 Netscape 格式 cookie jar，供 fetch.py 复用。

用法：
  python scripts/institutional_login.py <login-url> [-o cookie-jar路径] [extra-domains...]

  login-url      EZproxy 登录页或机构 SSO 入口，例如
                 https://ezproxy.library.univ.edu/login
                 （不知道入口？用学校图书馆数据库页面的 "校外访问" / "EZproxy"
                 链接；IEEE/Springer 的 "Access through your institution" 也可）
  -o/--output    输出 cookie jar 路径（默认 <skill_dir>/.scholar_institutional/cookies.txt）
  extra-domains  额外需要抓取 cookie 的域名，如 ieeexplore.ieee.org link.springer.com

流程：
  1. 打开一个可见的 stealth 浏览器窗口（CloakBrowser，需已安装 cloakbrowser 包）
  2. 你在窗口里完成机构登录（含 MFA），直到看到已登录页面
  3. 回到终端按回车 -> 脚本抓取会话 cookie 并写入 cookie jar
  4. 之后运行 fetch.py 前设置：
       PAPER_FETCH_INSTITUTIONAL=1
       PAPER_FETCH_EZPROXY=https://ezproxy.<你的学校>.edu   （用 EZproxy 时）
     fetch.py 会自动加载 cookie jar（PAPER_FETCH_COOKIE_JAR 可覆盖默认路径）

安全说明：
  - 只保存登录后的会话 cookie，绝不保存账号密码；
  - cookie jar 默认放在 <skill_dir>/.scholar_institutional/（已被 .gitignore 排除）；
  - cookie 会过期，过期后重新运行本向导即可（不会影响已保存的 key）。
"""
from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path
from _cloak_env import CLOAK_HINT, resolve_cloak_python

SKILL_DIR = Path(__file__).resolve().parent.parent
DEFAULT_JAR = SKILL_DIR / ".scholar_institutional" / "cookies.txt"


def _netscape_escape(value: str) -> str:
    # Netscape format: tab-separated; a cookie value containing tabs/newlines
    # would corrupt the file, so strip control characters.
    return "".join(ch for ch in value if ch not in "\t\r\n")


def _write_netscape_jar(cookies: list[dict], path: Path) -> int:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by scholar institutional_login.py - session cookies only",
    ]
    written = 0
    for c in cookies:
        name = c.get("name", "")
        value = _netscape_escape(str(c.get("value", "")))
        domain = c.get("domain", "")
        if not name or not domain:
            continue
        path_val = c.get("path") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expires") or 0)
        if expires <= 0:
            expires = 0  # session cookie
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        lines.append("\t".join([domain, include_sub, path_val, secure, str(expires), name, value]))
        written += 1
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return written


def main() -> int:
    ap = argparse.ArgumentParser(description="scholar 机构认证登录向导")
    ap.add_argument("login_url", help="EZproxy 登录页或机构 SSO 入口 URL")
    ap.add_argument("-o", "--output", default=str(DEFAULT_JAR), help="输出 cookie jar 路径")
    ap.add_argument("extra_domains", nargs="*", help="额外抓取 cookie 的域名")
    args = ap.parse_args()

    url = args.login_url.strip()
    if not (url.startswith("http://") or url.startswith("https://")):
        print("login-url 必须是 http(s) 链接", file=sys.stderr)
        return 2
    out = Path(args.output)

    # ---- CloakBrowser 依赖：自动选择装有 cloakbrowser 的解释器 ----
    py, tried = resolve_cloak_python()
    if py is None:
        print(f"[login] 未找到能 import cloakbrowser 的 Python 解释器。已探测: {', '.join(tried) or '无'}", file=sys.stderr)
        print(CLOAK_HINT, file=sys.stderr)
        return 1
    if os.path.normcase(os.path.abspath(py)) != os.path.normcase(os.path.abspath(sys.executable)):
        print(f"[login] 当前解释器缺少 cloakbrowser，自动改用: {py}", file=sys.stderr)
        return subprocess.call([py, str(Path(__file__).resolve())] + sys.argv[1:])
    from cloakbrowser import launch

    browser = None
    try:
        print(f"[login] 正在打开可见浏览器: {url}")
        browser = launch(headless=False)
        ctx = browser.new_context(accept_downloads=False)
        page = ctx.new_page()
        page.goto(url, wait_until="domcontentloaded", timeout=120_000)
        print("[login] 请在浏览器窗口内完成机构登录（含 MFA），直到进入已登录页面。")
        print("[login] 登录完成后，回到本终端按回车键继续 ...")
        try:
            input()
        except EOFError:
            print("[login] 未检测到回车（非交互终端），等待 120 秒后继续 ...", file=sys.stderr)
            import time
            time.sleep(120)

        cookies = ctx.cookies()
        wanted = {url.split("//")[1].split("/")[0].lower()}
        for d in args.extra_domains:
            wanted.add(d.strip().lower().lstrip("."))
        keep = []
        for c in cookies:
            dom = str(c.get("domain", "")).lower().lstrip(".")
            if any(dom == w or dom.endswith("." + w) or w.endswith("." + dom) for w in wanted):
                keep.append(c)
        if not keep:
            print("[login] 警告：未抓到目标域名的 cookie，可能未登录成功。", file=sys.stderr)
            print("[login] 已抓到以下域名的 cookie: " + ", ".join(sorted({str(c.get('domain','')) for c in cookies}) or ["无"]), file=sys.stderr)
        n = _write_netscape_jar(keep, out)
        print(f"[login] 已写入 {n} 条会话 cookie -> {out}")
        print("[login] 下一步：")
        print("  PAPER_FETCH_INSTITUTIONAL=1  (必设)")
        print("  PAPER_FETCH_EZPROXY=<你的EZproxy域名>  (用 EZproxy 时设置)")
        print("  然后运行 scripts/fetch.py <DOI> 即可带机构权限下载。")
        return 0
    except Exception as e:
        print(f"[login] 失败: {e}", file=sys.stderr)
        return 1
    finally:
        if browser is not None:
            try:
                browser.close()
            except Exception:
                pass


if __name__ == "__main__":
    sys.exit(main())
